version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: sso
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1999:1999"
      - "8080:8080"