env: "local"
data_provider: "mysql"
mysql_settings:
  host: "db"
  port: 3306
  user: "root"
  password: "password"
  db: "sso"
token_ttl: 1h
grpc:
  port: 1999
  timeout: 10h
http:
  http_port: 8080
  timeout: 10h